export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/'
export const BASKET_ROUTE= '/basket'
export const DEVICE_ROUTE = '/device'
export const ABOUT_ROUTE = '/about';
export const SERVICES_ROUTE = '/services';
export const FAQ_ROUTE = '/faq';
export const PAIMENTDELIVERY_ROUTE = '/payment-delivery';
export const SEARCH_ROUTE = '/search';
